[workspace]
resolver = "2"
members = [
    "derive_common",
    "malloc_size_of",
    "rustfmt.toml",
    "selectors",
    "servo_arc",
    "style",
    "style_derive",
    "style_static_prefs",
    "style_traits",
    "to_shmem",
    "to_shmem_derive",
]
default-members = ["style"]

[workspace.dependencies]
accountable-refcell = "0.2.0"
app_units = "0.7"
content-security-policy = { version = "0.5", features = ["serde"] }
crossbeam-channel = "0.5"
cssparser = "0.34"
darling = { version = "0.20", default-features = false }
euclid = "0.22"
http = "0.2"
indexmap = { version = "2.2.2", features = ["std"] }
keyboard-types = "0.7"
lazy_static = "1.4"
malloc_size_of_derive = "0.1"
markup5ever = "0.12"
proc-macro2 = "1"
quote = "1"
serde = "1.0.195"
serde_bytes = "0.11"
smallbitvec = "2.3.0"
smallvec = "1.13"
string_cache = "0.8"
string_cache_codegen = "0.5"
syn = { version = "2", default-features = false, features = ["clone-impls", "derive", "parsing"] }
synstructure = "0.13"
thin-vec = "0.2.13"
time = "0.1.41"
tokio = "1"
url = { version = "2.5", features = ["serde"] }
uuid = { version = "1.7.0", features = ["v4"] }
webrender_api = { git = "https://github.com/servo/webrender", branch = "0.64" }
xml5ever = "0.18"
