[package]
name = "stylo_traits"
version = "0.1.0"
authors = ["The Servo Project Developers"]
documentation = "https://docs.rs/stylo_traits/"
description = "Vocabulary types for the Stylo CSS engine"
repository = "https://github.com/servo/stylo"
keywords = ["css", "style"]
license = "MPL-2.0"
edition = "2015"

[lib]
name = "stylo_traits"
path = "lib.rs"

[features]
servo = ["servo_atoms", "cssparser/serde", "url", "euclid/serde"]
gecko = []

[dependencies]
app_units = "0.7"
bitflags = "2"
cssparser = "0.34"
euclid = "0.22"
lazy_static = "1"
malloc_size_of = { version = "0.1", path = "../malloc_size_of", package = "stylo_malloc_size_of" }
malloc_size_of_derive = "0.1"
selectors = { version = "0.26", path = "../selectors", package = "stylo_selectors" }
serde = "1.0"
servo_arc = { path = "../servo_arc", version = "0.4", package = "stylo_arc" }
servo_atoms = { version = "0.1", path = "../atoms", package = "stylo_atoms", optional = true }
thin-vec = "0.2"
to_shmem = { version = "0.1", path = "../to_shmem", package = "stylo_to_shmem" }
to_shmem_derive = { version = "0.1", path = "../to_shmem_derive", package = "stylo_to_shmem_derive" }
url = { version = "2.5", optional = true }
