[package]
name = "selectors"
version = "0.24.0"
authors = ["The Servo Project Developers"]
documentation = "https://docs.rs/selectors/"
description = "CSS Selectors matching for Rust"
repository = "https://github.com/servo/servo"
readme = "README.md"
keywords = ["css", "selectors"]
license = "MPL-2.0"
build = "build.rs"

[lib]
name = "selectors"
path = "lib.rs"

[features]
bench = []

[dependencies]
bitflags = "2"
cssparser = { workspace = true }
derive_more = { version = "0.99", default-features = false, features = ["add", "add_assign"] }
fxhash = "0.2"
log = "0.4"
new_debug_unreachable = "1"
phf = "0.11"
precomputed-hash = "0.1"
servo_arc = { version = "0.2", path = "../servo_arc" }
size_of_test = { path = "../size_of_test" }
smallvec = "1.0"
to_shmem = { version = "0.0.1", path = "../to_shmem" }
to_shmem_derive = { version = "0.0.1", path = "../to_shmem_derive" }

[build-dependencies]
phf_codegen = "0.11"
