[package]
name = "stylo_malloc_size_of"
version = "0.1.1"
authors = ["The Servo Project Developers"]
documentation = "https://docs.rs/stylo_malloc_size_of/"
description = "Support crate for Stylo CSS engine"
repository = "https://github.com/servo/stylo"
keywords = ["css", "style"]
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
path = "lib.rs"

[features]
servo = [
    "accountable-refcell",
    "content-security-policy",
    "crossbeam-channel",
    "http",
    "indexmap",
    "keyboard-types",
    "serde",
    "serde_bytes",
    "string_cache",
    "url",
    "uuid",
    "xml5ever",
]
gecko = ["thin-vec/gecko-ffi"]

[dependencies]
accountable-refcell = { version = "0.2.0", optional = true }
app_units = "0.7"
content-security-policy = { version = "0.5", features = ["serde"], optional = true }
crossbeam-channel = { version = "0.5", optional = true }
cssparser = "0.34"
dom = { path = "../dom", version = "0.1", package = "stylo_dom" }
euclid = "0.22"
http = { version = "0.2", optional = true }
indexmap = { version = "2.2", optional = true }
keyboard-types = { version = "0.7", optional = true }
selectors = { version = "0.26", path = "../selectors", package = "stylo_selectors" }
serde = { version = "1.0.195", optional = true }
serde_bytes = { version = "0.11", optional = true }
servo_arc = { path = "../servo_arc", version = "0.4", package = "stylo_arc" }
smallbitvec = "2.3.0"
smallvec = "1.13"
string_cache = { version = "0.8", optional = true }
thin-vec = { version = "0.2.13" }
tokio = { version = "1", features = ["sync"] }
url = { version = "2.5", features = ["serde"], optional = true }
uuid = { version = "1.7.0", optional = true }
void = "1.0.2"
xml5ever = { version = "0.20", optional = true }
