name: Sync

on:
  # schedule:
  #   - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/cache@v3
        with:
          path: cache/upstream
          key: upstream
      - run: |
          ./sync.sh filtered
          git fetch -f --progress ./filtered master:upstream
          git push -fu --progress origin upstream
